- hosts: localhost
  tasks:
    - name: Ensure Docker service is running
      win_service:
        name: com.docker.service
        state: started
        enabled: yes

    - name: Ensure Node API is running as service
      win_nssm:
        name: NodeAPI
        path: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
        arguments: Start-Process docker-compose -d
        start_mode: auto
